ignore:
  - "src/main/scala/io.github.mitchelllisle/Main|Solution.scala"  # ignore folders and all its contents
comment:
  layout: "header, reach, diff, files, footer"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes